### ISSUE TITLE
[BUG] Vineyard's builders and resolvers for python types doesn't fit very well with python itself (and numpy, pandas)

### ISSUE THREAD

**Issue by sighingnow** [alibaba/libvineyard#136]
**Describe your problem**

- [x] Vineyard python client crashes when get empty `np.array` from vineyard (#137).

  ```python
  In [1]: import vineyard
  
  In [2]: cl = vineyard.connect("/tmp/vineyard.sock")
  
  In [3]: cl.put(np.array(()))
  Out[3]: o00019a42596292fc
  
  In [4]: cl.get(cl.put(np.array(())))
  WARNING: Logging before InitGoogleLogging() is written to STDERR
  I0108 12:57:40.512176 342670784 object_factory.cc:26] Failed to create an instance due to the unknown typename: vineyard::Tensor<float64>
  [1]    14403 segmentation fault  ipython
  ```

- [x] vary-sized tuple (#137)
- [ ] numpy ndarray with OBJECT type (hard to fixes).
- [ ] sparse arrays are stored in a continous flatten manner
- [x] tensor order (easy to fixes) (#137)
- [ ] string type.
   + [ ] fixed-sized string / fixed-sized binary type
   + [ ] vary-sized string / python object

**Additional context**

N/A
